# Generated by Django 5.1.4 on 2026-04-22 10:10

import apps.core.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0002_apartmenttype_badge_constructionstage_decoration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('title', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='Адрес')),
                ('description', apps.core.fields.I18nField(blank=True, default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Описание')),
                ('banks', models.JSONField(blank=True, default=list, verbose_name='Банки')),
                ('contract_number_index', models.PositiveIntegerField(default=0, help_text='Последний выданный порядковый номер договора в рамках ЖК.', verbose_name='Счётчик договоров')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='references.developer', verbose_name='Застройщик')),
            ],
            options={
                'verbose_name': 'Жилой комплекс',
                'verbose_name_plural': 'Жилые комплексы',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('title', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('number', models.CharField(blank=True, max_length=32, verbose_name='Номер корпуса')),
                ('cadastral_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Кадастровый номер')),
                ('date_of_issue', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('planning_file', models.FileField(blank=True, null=True, upload_to='objects/buildings/planning/', verbose_name='Файл планировки корпуса')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='objects.project', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ['project_id', 'sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('title', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер подъезда')),
                ('planning_file', models.FileField(blank=True, null=True, upload_to='objects/sections/planning/', verbose_name='Файл планировки подъезда')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='objects.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Подъезд',
                'verbose_name_plural': 'Подъезды',
                'ordering': ['building_id', 'sort', 'number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('number', models.SmallIntegerField(help_text='Может быть отрицательным для подземных уровней.', verbose_name='Номер этажа')),
                ('price_per_sqm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена за м²')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floors', to='objects.section', verbose_name='Подъезд')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
                'ordering': ['section_id', 'number', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='objects_section_unique_number_per_building'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('section', 'number'), name='objects_floor_unique_number_per_section'),
        ),
    ]
