# Generated by Django 5.1.4 on 2026-04-22 10:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('references', '0002_apartmenttype_badge_constructionstage_decoration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('number', models.CharField(db_index=True, help_text='Строка, т.к. в легаси встречаются буквы (12А).', max_length=32, verbose_name='Номер квартиры')),
                ('rooms_count', models.PositiveSmallIntegerField(default=1, verbose_name='Число комнат')),
                ('area', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Площадь, м²')),
                ('total_bti_area', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='БТИ-площадь, м²')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Обновляется сервисом pricing при изменении цены этажа.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Итоговая цена, UZS')),
                ('surcharge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Разовая наценка для данной квартиры (не %).', max_digits=14, verbose_name='Наценка, UZS')),
                ('is_duplex', models.BooleanField(default=False, verbose_name='Дуплекс')),
                ('is_studio', models.BooleanField(default=False, verbose_name='Студия')),
                ('is_euro_planning', models.BooleanField(default=False, verbose_name='Европлан')),
                ('planning_file', models.FileField(blank=True, null=True, upload_to='objects/apartments/planning/', verbose_name='Файл планировки')),
                ('status', models.CharField(choices=[('free', 'Свободно'), ('booked', 'Забронировано'), ('booked_vip', 'Бронь руководства'), ('formalized', 'Оформлено'), ('escrow', 'Эскроу'), ('sold', 'Продано')], db_index=True, default='free', max_length=16, verbose_name='Статус')),
                ('booking_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Заполняется при бронировании; пустая для других статусов.', null=True, verbose_name='Бронь истекает')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('characteristics', models.ManyToManyField(blank=True, related_name='apartments', to='references.badge', verbose_name='Характеристики (теги)')),
                ('decoration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='references.decoration', verbose_name='Отделка')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments', to='objects.floor', verbose_name='Этаж')),
                ('occupied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='references.occupiedby', verbose_name='Категория занятости')),
                ('output_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='references.outputwindows', verbose_name='Вид из окон')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['floor_id', 'sort', 'number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=16, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=16, verbose_name='Новый статус')),
                ('comment', models.CharField(blank=True, max_length=512, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='objects.apartment', verbose_name='Квартира')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartment_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Запись лога статусов',
                'verbose_name_plural': 'Лог статусов квартир',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('floor', 'number'), name='objects_apartment_unique_number_per_floor'),
        ),
        migrations.AddIndex(
            model_name='apartmentstatuslog',
            index=models.Index(fields=['apartment', '-created_at'], name='objects_apa_apartme_5fbb27_idx'),
        ),
    ]
