# Generated by Django 5.1.4 on 2026-04-22 10:56

import apps.core.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_apartment_apartmentstatuslog_and_more'),
        ('references', '0002_apartmenttype_badge_constructionstage_decoration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('down_payment_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Первый взнос, %')),
                ('installment_months', models.PositiveSmallIntegerField(default=0, verbose_name='Срок рассрочки, мес.')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='objects.project', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'План оплаты',
                'verbose_name_plural': 'Планы оплаты',
                'ordering': ['project_id', 'sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Применённая скидка, %')),
                ('installment_months', models.PositiveSmallIntegerField(default=0, verbose_name='Срок рассрочки, мес.')),
                ('new_price_per_sqm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена за м² после скидки')),
                ('new_total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Итоговая цена')),
                ('initial_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Первый взнос')),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ежемесячный платёж')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='objects.apartment', verbose_name='Квартира')),
                ('payment_percent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='references.paymentinpercent', verbose_name='Процент оплаты')),
            ],
            options={
                'verbose_name': 'Расчёт',
                'verbose_name_plural': 'Расчёты по квартирам',
                'ordering': ['apartment_id', 'payment_percent_id'],
                'constraints': [models.UniqueConstraint(fields=('apartment', 'payment_percent'), name='objects_calculation_unique_apt_payment_percent')],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('area_start', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Площадь от, м²')),
                ('area_end', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Площадь до, м²')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Скидка, %')),
                ('is_duplex', models.BooleanField(default=False, help_text='Правило применяется только к квартирам-дуплексам.', verbose_name='Для дуплексов')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('payment_percent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_rules', to='references.paymentinpercent', verbose_name='Процент оплаты')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_rules', to='objects.project', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Правило скидок',
                'verbose_name_plural': 'Правила скидок',
                'ordering': ['project_id', 'sort', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('area_end__gte', models.F('area_start'))), name='objects_discountrule_area_end_gte_start')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Старая цена за м²')),
                ('new_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Новая цена за м²')),
                ('comment', models.CharField(blank=True, max_length=512, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_price_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='objects.floor', verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Запись истории цен',
                'verbose_name_plural': 'История цен',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['floor', '-created_at'], name='objects_pri_floor_i_b0c4db_idx')],
            },
        ),
    ]
