# Generated by Django 5.1.4 on 2026-04-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_paymentplan_calculation_discountrule_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_number_prefix',
            field=models.CharField(blank=True, default='', help_text='Пример: «ЯМ» → ЯМ-00001. Пусто — выдаём только номер без префикса.', max_length=10, verbose_name='Префикс номера договора'),
        ),
    ]
