# Generated by Django 5.1.4 on 2026-04-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_project_contract_number_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='planning_file',
        ),
    ]
