# Generated by Django 5.1.4 on 2026-04-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_remove_apartment_planning_file'),
        ('references', '0003_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='references.planning', verbose_name='Планировка'),
        ),
    ]
