# Generated by Django 5.1.4 on 2026-04-24 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_apartment_planning'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('file', models.ImageField(upload_to='objects/buildings/photos/%Y/%m/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Минимальное значение — обложка.', verbose_name='Порядок')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='objects.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Фото корпуса',
                'verbose_name_plural': 'Фото корпусов',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('file', models.ImageField(upload_to='objects/projects/photos/%Y/%m/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Минимальное значение — обложка.', verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='objects.project', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Фото ЖК',
                'verbose_name_plural': 'Фото ЖК',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
