# Generated by Django 5.1.4 on 2026-04-21 13:11

import apps.core.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n, apps.core.fields.validate_i18n], verbose_name='Название')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('permissions', models.JSONField(default=dict, verbose_name='Разрешения')),
                ('allowed_payment_types', models.JSONField(default=list, help_text='Список: bank / cash / barter', verbose_name='Разрешённые типы оплаты')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['full_name', 'email'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', 'Oʻzbekcha'), ('oz', 'Ўзбекча')], default='ru', max_length=2, verbose_name='Язык интерфейса'),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +998XXXXXXXXX.', regex='^\\+?998\\d{9}$')], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='staff',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', max_length=5, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='users.role', verbose_name='Роль'),
        ),
    ]
