# Generated by Django 5.1.4 on 2026-04-22 07:21

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_alter_staff_options_remove_staff_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название'),
        ),
    ]
