# Generated by Django 5.1.4 on 2026-04-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], db_index=True, max_length=8, verbose_name='Метод')),
                ('path', models.CharField(db_index=True, max_length=512, verbose_name='Путь')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='HTTP статус')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Тело запроса')),
                ('response_summary', models.JSONField(blank=True, default=dict, verbose_name='Ответ (обрезка)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
            },
        ),
    ]
