# Generated by Django 5.1.4 on 2026-04-22 07:35

import apps.core.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип помещения',
                'verbose_name_plural': 'Типы помещений',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
                ('color', models.CharField(blank=True, help_text='Hex, напр. #22C55E', max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RGB или #RRGGBB.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тег (бейдж)',
                'verbose_name_plural': 'Теги квартир',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Этап строительства',
                'verbose_name_plural': 'Этапы строительства',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип отделки',
                'verbose_name_plural': 'Типы отделки',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Материал дома',
                'verbose_name_plural': 'Материалы дома',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccupiedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Кем занято',
                'verbose_name_plural': 'Категории занятости',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputWindows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вид из окна',
                'verbose_name_plural': 'Виды из окон',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentInPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
                ('percent', apps.core.fields.PercentField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Шаг процента оплаты',
                'verbose_name_plural': 'Шкала процентов оплаты',
                'ordering': ['percent'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremisesDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Отделка помещений',
                'verbose_name_plural': 'Отделки помещений',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип планировки (комнатность)',
                'verbose_name_plural': 'Типы планировок',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='references.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
    ]
