# Generated by Django 5.1.4 on 2026-04-24 10:27

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_remove_apartment_planning_file'),
        ('references', '0002_apartmenttype_badge_constructionstage_decoration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('rooms_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Комнат')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Площадь, м²')),
                ('image_2d', models.ImageField(blank=True, null=True, upload_to='references/plannings/2d/%Y/%m/', verbose_name='Изображение 2D')),
                ('image_3d', models.ImageField(blank=True, null=True, upload_to='references/plannings/3d/%Y/%m/', verbose_name='Изображение 3D')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plannings', to='objects.project', verbose_name='ЖК')),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
                'ordering': ['sort', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('project', 'code'), name='refs_planning_unique_code_per_project')],
            },
        ),
    ]
