# Generated by Django 5.1.4 on 2026-04-22 12:39

import apps.core.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа клиентов',
                'verbose_name_plural': 'Группы клиентов',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', apps.core.fields.I18nField(default=apps.core.fields.empty_i18n, validators=[apps.core.fields.validate_i18n], verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Чем меньше — тем выше в списке', verbose_name='Порядок')),
                ('color', models.CharField(blank=True, help_text='Любой CSS-цвет или пресет из chip палитры.', max_length=16, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Статус клиента',
                'verbose_name_plural': 'Статусы клиентов',
                'ordering': ['sort', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('entity', models.CharField(choices=[('phys', 'Физ. лицо'), ('jur', 'Юр. лицо')], db_index=True, default='phys', max_length=8, verbose_name='Тип')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], help_text='Применимо только для физ. лица.', max_length=8, verbose_name='Пол')),
                ('full_name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО / Название')),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None, verbose_name='Телефоны')),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=128), blank=True, default=list, size=None, verbose_name='Email-адреса')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=16, verbose_name='ИНН')),
                ('oked', models.CharField(blank=True, max_length=16, verbose_name='ОКЭД')),
                ('pin', models.CharField(blank=True, db_index=True, help_text='Персональный идентификационный номер физ. лица.', max_length=16, verbose_name='ПИНФЛ')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Заметки')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('groups', models.ManyToManyField(blank=True, related_name='clients', to='clients.clientgroup', verbose_name='Группы')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.clientstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('role', models.CharField(blank=True, help_text='Например: директор, главный бухгалтер, подписант.', max_length=128, verbose_name='Роль')),
                ('is_chief', models.BooleanField(default=False, verbose_name='Главный подписант')),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None, verbose_name='Телефоны')),
                ('email', models.EmailField(blank=True, max_length=128, verbose_name='Email')),
                ('passport', models.JSONField(blank=True, default=dict, verbose_name='Паспортные данные')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('inn', models.CharField(blank=True, max_length=16, verbose_name='ИНН')),
                ('pin', models.CharField(blank=True, max_length=16, verbose_name='ПИНФЛ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Контакт клиента',
                'verbose_name_plural': 'Контакты клиентов',
                'ordering': ['-is_chief', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('type', models.CharField(choices=[('internal', 'Внутренний'), ('local', 'Местный')], db_index=True, default='local', max_length=16, verbose_name='Тип')),
                ('bank_requisite', models.JSONField(blank=True, default=dict, verbose_name='Банковские реквизиты')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Банковский реквизит',
                'verbose_name_plural': 'Банковские реквизиты',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['entity', 'full_name'], name='clients_cli_entity_571fda_idx'),
        ),
    ]
