# Generated by Django 5.1.4 on 2026-04-23 06:28

import apps.core.fields
import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('objects', '0003_paymentplan_calculation_discountrule_pricehistory'),
        ('references', '0002_apartmenttype_badge_constructionstage_decoration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('contract_number', models.CharField(blank=True, db_index=True, default='', help_text='Уникален в рамках ЖК. Пусто — черновик без номера.', max_length=50, verbose_name='Номер договора')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата договора')),
                ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено клиенту')),
                ('related_person', models.CharField(blank=True, help_text='Свободный текст; используется, если подписант не заведён как контакт.', max_length=255, verbose_name='Физлицо-подписант (доп.)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('total_amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма договора')),
                ('down_payment', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Первый взнос')),
                ('action', models.CharField(choices=[('request', 'Запрос'), ('wait', 'На согласовании'), ('edit', 'На редактировании'), ('approve', 'Утверждён'), ('sign_in', 'Подписан')], db_index=True, default='request', max_length=16, verbose_name='Статус workflow')),
                ('is_signed', models.BooleanField(db_index=True, default=False, verbose_name='Подписан')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('is_mortgage', models.BooleanField(default=False, verbose_name='Ипотека')),
                ('requisite', models.JSONField(blank=True, default=dict, verbose_name='Реквизиты продавца (snapshot)')),
                ('document', models.JSONField(blank=True, default=dict, verbose_name='Заполненные поля (snapshot)')),
                ('old', models.JSONField(blank=True, default=list, verbose_name='Предыдущие версии')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/pdf/', verbose_name='PDF договора')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='contracts/qr/', verbose_name='QR-код')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='objects.apartment', verbose_name='Квартира')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('calculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='objects.calculation', verbose_name='Расчёт')),
                ('payment_methods', models.ManyToManyField(blank=True, related_name='contracts', to='references.paymentmethod', verbose_name='Способы оплаты')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='objects.project', verbose_name='ЖК')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_contracts', to='clients.clientcontact', verbose_name='Подписант (контакт клиента)')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='contract_templates/', verbose_name='Файл шаблона (.docx)')),
                ('placeholders', models.JSONField(blank=True, default=list, help_text='Список описаний полей: [{model, field, field_name, description}]', verbose_name='Плейсхолдеры')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Шаблон договора',
                'verbose_name_plural': 'Шаблоны договоров',
                'ordering': ['-modified_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('due_date', models.DateField(db_index=True, verbose_name='Срок оплаты')),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма к оплате')),
                ('paid_amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Оплачено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('partial', 'Частично оплачен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Пункт графика',
                'verbose_name_plural': 'График платежей',
                'ordering': ['contract_id', 'due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сумма')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Перечисление'), ('barter', 'Бартер')], db_index=True, default='cash', max_length=16, verbose_name='Канал оплаты')),
                ('paid_at', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Дата оплаты')),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Номер ПКО')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Кто зафиксировал')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.paymentschedule', verbose_name='Пункт графика')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['action', 'is_signed'], name='contracts_c_action_e57287_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['-date'], name='contracts_c_date_e029f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('contract_number', ''), _negated=True), fields=('project', 'contract_number'), name='contracts_contract_unique_project_number'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['contract', 'due_date'], name='contracts_p_contrac_b016c3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['status', 'due_date'], name='contracts_p_status_9278f6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['schedule', '-paid_at'], name='contracts_p_schedul_8b68c8_idx'),
        ),
    ]
