# Generated by Django 5.1.4 on 2026-04-23 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('objects', '0004_project_contract_number_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'ordering': ['project_id', '-modified_at', 'id'], 'verbose_name': 'Шаблон договора', 'verbose_name_plural': 'Шаблоны договоров'},
        ),
        migrations.RemoveField(
            model_name='contracttemplate',
            name='file',
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Используется сервисом docgen для рендера PDF. Если пусто — PDF сгенерировать нельзя; менеджер обязан выбрать шаблон (глобальный или для этого ЖК) перед генерацией.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.contracttemplate', verbose_name='Шаблон договора'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='body',
            field=models.TextField(blank=True, default='', help_text='HTML, сохранённый Tiptap-редактором. Плейсхолдеры — {{key}}; соответствия key → path задаются ниже в placeholders.', verbose_name='HTML-шаблон'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Пусто — глобальный шаблон, доступен любому контракту.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates', to='objects.project', verbose_name='ЖК'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=list, help_text='Список объектов [{"key": "...", "path": "...", "label": "..."}]. key используется в {{…}}, path — дотточный путь в контексте контракта.', verbose_name='Плейсхолдеры'),
        ),
    ]
