# Generated by Django 5.1.4 on 2026-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contracttemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='file',
            field=models.FileField(blank=True, help_text='Word-файл с тегами Jinja2 вида {{ contract.contract_number }}. Рендерится в PDF через docxtpl + LibreOffice.', null=True, upload_to='contract_templates/docx/%Y/%m/', verbose_name='DOCX-файл'),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='source',
            field=models.CharField(choices=[('html', 'HTML (встроенный редактор)'), ('docx', 'DOCX (Word-файл)')], db_index=True, default='html', help_text='html — шаблон редактируется в Tiptap в браузере; docx — юрист загружает .docx, из которого рендерится PDF.', max_length=8, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='body',
            field=models.TextField(blank=True, default='', help_text='HTML, сохранённый Tiptap-редактором. Используется только для source=html. Плейсхолдеры — {{key}}.', verbose_name='HTML-шаблон'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='placeholders',
            field=models.JSONField(blank=True, default=list, help_text='Для html-шаблонов — список [{"key": "...", "path": "...", "label": "..."}]. Для docx — автоматически собранный список тегов, найденных в файле (для отображения в каталоге плейсхолдеров).', verbose_name='Плейсхолдеры'),
        ),
    ]
