# Generated by Django 5.1.4 on 2026-04-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contracttemplate_file_contracttemplate_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client_note',
            field=models.TextField(blank=True, verbose_name='Заметки по клиенту'),
        ),
    ]
